
name: Release
on:
  push:
    branches:
    - release
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Installing dependencies
        run: make install
      - name: Generating wheel
        run: poetry build
      - name: Uploading to pypy
        run: poetry publish --username {{ '${{ secrets.PYPI_USER }}' }} --password "{{ '${{ secrets.PYPI_PASSWORD }}' }}"
  docs:
    runs-on: ubuntu-latest